### ISSUE TITLE
Define global Python functions and classes

### ISSUE THREAD

**Issue by gaow** [bpeng2000/SOS#8]
I can see it might be helpful to allow for definition of functions or classes in `[parameter]`. For example, 

```
[parameters]
def get_variable_names(val):
    ...
    return val_names
```

Then 

```
[1]
input: get_variable_names(${val})
```

This may handle something more complicated than what a lambda function can do.

**Comment by bpeng2000** [comment]
Perhaps i should not call it global because every definition is global. I
do not want to encourage function definition because sos uses slightly
modified syntax. For this particular problem did you try to do it within a
step?

**Comment by gaow** [comment]
Oh are you suggesting that it is possible to define class / functions within each step, before `input:`? The goal here is to make it possible to obtain input names smartly. I did manage to do it with a conventional one liner Python code. I am just wondering if more flexibility is allowed.

**Comment by bpeng2000** [comment]
A step does not have to have input etc so you can have action-only steps
for class definition.. The parse is not strong enough for class definition
at this point, I am working on it.

Bo

**Comment by bpeng2000** [comment]
Fixed.

The problem here is that Python code in SoS allows interpolation but only
at a block level. That is to say

for key in values:
    print('${key}')

would fail because ${key} is handled before the two lines are sent to
Python. This is the only case these code would fail though.

I can enable function definition even execution in global and parameter,
then no section needs to be defined, and a regular python script would just
work... :-)

Bo

**Comment by bpeng2000** [comment]
Ok, arbitrary statement can now be defined in global section.

Bo

**Comment by gaow** [comment]
This is great! For the script I was working on I got away with lambda function but I'll try this new feature for more complex procedures. But I'm still not getting where I should define it ... is there an example on the wiki yet?

**Comment by bpeng2000** [comment]
Rules for now:

1. anything can be done in global (in section definition), except that SoS
changes python syntax a bit (interpolation with restriction, '' as raw)
2. only definitions is allowed in parameters, but definitions in global
section can be used in parameters.
3. only assignment is allowed before directives (input: etc).
4. nothing is allowed between directives
5. anything can be done after directive (or if the section does not have
any directive).

This allows SoS to execute any python code in its own flavor (treatment of
raw string and interpolation). If this is problematic
1. use a python interpreter to execute the sos script. :-)
2. quote the code with python(''', ''') but this does not always work if
the code contains ''' '''

Bo
​

**Comment by bpeng2000** [comment]
Then users should be aware of differences between sos/python2 and
sos/python3 ..., which is something I do not want to go into and why I
tried to restrict statements in sos. We can do something like

#fileformat=SOS1.0  <- compatible mode

#fileformat=SOS1.0py2 <- only works for python2 version of SoS
#fileformat=SOS1.0py3 <- only works for python3 version of SoS

but this is ugly.

Bo

**Comment by bpeng2000** [comment]
This is also fixed, so a majority of Python code should be executed
correctly in SoS.

Bo
